name: Default actions on commit
on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 17.x, 16.x, 15.x]
        mongodb-version: ['6.0', '5.0', '4.4']

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 27017
      - name: Run tests and collect coverage
        working-directory: ${{github.workspace}}
        run: npm test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
